config/routes.rb
Photograph::Application.routes.draw do
 
 

  get "adminusersession/create"

  get "adminusersession/destroy"

  

  resources :adminusers

  resources :mainusers

  get 'adminuserpage' => 'adminuserpage#index'

  controller :adminusersession do
    get 'adminuserlogin' => :new
    post 'adminuserlogin' => :create
   delete 'adminuserlogout' => :destroy
  end

  get 'mainuserpage' => 'mainuserpage#index'

  controller :mainusersession do
    get 'userlogin' => :new
    post 'userlogin' => :create
   delete 'userlogout' => :destroy
  end

    get 'admin' => 'admin#index'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
   delete 'logout' => :destroy
end

  scope '(:locale)' do
  resources :users

  resources :orders

  resources :line_items

  resources :carts
  
  resources :photos do
    get :who_bought, :on => :member
    get :sample_image, :on => :member
    get :original_image, :on => :member
    
  end

  root :to => 'store#index', :as => 'store'

  end
  get "sessions/new"
  get "sessions/create"
  get "sessions/destroy"
  get "store/index"

end

app/models/photo.rb
class Photo < ActiveRecord::Base
  default_scope :order => 'Title'
  has_many :line_items
  has_many :orders, :through => :line_items

  
  attr_reader :sample_image
  before_destroy :ensure_not_referenced_by_any_line_item
   
  
  validates :Title, :Description, :Location, :Date_and_time, :Photographer_name,
   :single_price, :outright_price, :presence => true
  validates :Title, :uniqueness => true
  validates :single_price, :outright_price, :numericality =>
    {:greater_than_or_equal_to => 0.01}
 
  
  def sample_image=(photo_field)
    #self.name =~ /\.(jpeg|jpg|gif|png)$/i
    self.content_type = photo_field.content_type.to_s.chomp
     self.snap = photo_field.read
   end

  def original_image=(photo_field)
    #self.name =~ /\.(jpeg|jpg|gif|png)$/i
    self.content_type = photo_field.content_type.to_s.chomp
     self.realsnap = photo_field.read
   end
   

  
          private
          # ensure that there are no line items referencing this product
            def ensure_not_referenced_by_any_line_item
              if line_items.empty?
                 return true
              else
                 errors.add(:base, 'Line Items present')
                 return false
              end
          end
   def self.search(search)
    if search
     find(:all, :conditions => ['Title LIKE ? or Photographer_name LIKE ?', "%#{search}%", "%#{search}%"])
    else
     find(:all)
    end
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  skip_before_filter :userauthorize
  skip_before_filter :adminuserauthorize
  skip_before_filter :authorize
  # GET /photos
  # GET /photos.xml
   
  def index
    @photos = Photo.search(params[:search])
    

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @photos }
    end
  end
  


  # GET /photos/1
  # GET /photos/1.xml
  def show
    @photo = Photo.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @photo }
    end
  end

  # GET /photos/new
  # GET /photos/new.xml
  def new
    @photo = Photo.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @photo }
    end
  end

  # GET /photos/1/edit
  def edit
    @photo = Photo.find(params[:id])
  end

  # POST /photos
  # POST /photos.xml
  def create
    @photo = Photo.new(params[:photo])

    respond_to do |format|
      if @photo.save
        format.html { redirect_to(@photo,
            :notice => 'Photo was successfully created.') }
        format.xml  { render :xml => @photo, :status => :created,
          :location => @photo }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @photo.errors,
          :status => :unprocessable_entity }
      end
    end
  end

  # PUT /photos/1
  # PUT /photos/1.xml
  def update
    @photo = Photo.find(params[:id])

    respond_to do |format|
      if @photo.update_attributes(params[:photo])
        format.html { redirect_to(@photo,
            :notice => 'Photo was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @photo.errors,
          :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.xml
  def destroy
    @photo = Photo.find(params[:id])
    @photo.destroy

    respond_to do |format|
      format.html { redirect_to(photos_url) }
      format.xml  { head :ok }
    end
  end

  def who_bought
    @photo = Photo.find(params[:id])
    respond_to do |format|
      format.atom
      format.xml { render :xml => @photo }
    end
  end

  def sample_image
     @sample_image = Photo.find(params[:id])
     send_data(@sample_image.snap,
     :filename =>"sampleImage1.jpg" ,
     :content_type => @sample_image.content_type,
     :disposition => "inline")
 end

  def original_image
     @original_image = Photo.find(params[:id])
     send_data(@original_image.realsnap,
     :filename =>"sampleImage1.jpg" ,
     :content_type => @original_image.contente_type,
     :disposition => "inline")
 end


  
end

  
 

app/views/photos/index.html.erb
<div id="photo_list" >
<table>
  <% if session[:mainuser_id] %>
        <%= link_to 'New Photo', new_photo_path %>
     <% end %>

     <% if session[:adminuser_id] %>
        <%= link_to 'New Photo', new_photo_path %>
     <% end %>

  <% if session[:user_id] %>
        <%= link_to 'New Photo', new_photo_path %>
     <% end %>
<% @photos.each do |photo| %>
  <tr class="<%= cycle('list_line_odd', 'list_line_even') %>" >

    <td>
      <% if photo.snap %>
      <%= image_tag(url_for({:action => 'sample_image', :id => photo.id}),
      :class => 'list_image') %>
      <% end  %>
    </td>

    <td class="list_description">
      <dl>

    <dt><%= photo.Title %></dt>
    
    <dt><%= photo.Location %></dt>
    <dt><%= photo.Date_and_time %></dt>
    <dt><%= photo.Photographer_name %></dt>
    <dt><%= photo.single_price %></dt>
    <dt><%= photo.outright_price %></dt>
    <dd><%= truncate(strip_tags(photo.Description),
            :length => 100) %></dd>
      </dl>
    </td>

    <% if session[:user_id] %>
    <td class="list_actions" >
       <%= link_to 'Show', photo %><br/>
       <%= link_to 'Edit', edit_photo_path(photo) %><br/>
       <%= link_to 'Destroy', photo,
                   :confirm => 'Are you sure?',
                   :method => :delete %>
       <%= link_to 'hide', photo %>
    </td>
  <% end %>

    <% if session[:mainuser_id] %>
    <td class="list_actions" >
       <%= link_to 'Show', photo %><br/>
       <%= link_to 'Edit', edit_photo_path(photo) %><br/>
          </td>
  <% end %>


     <% if session[:adminuser_id] %>
      <td class="list_actions">

        <%= link_to 'Show', photo %><br/>
        <%= link_to 'Edit', edit_photo_path(photo) %><br/>
        <%= link_to 'Destroy', photo,
                   :confirm => 'Are you sure?',
                   :method => :delete %>
     </td>
     
     <% end %>

     
  </tr>
  
<% end %>
</table>
</div>
<br />



  

app/views/photos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @photo.Title %>
</p>

<p>
  <b>Description:</b>
  <%= @photo.Description %>
</p>

<p>
  <b>Location:</b>
  <%= @photo.Location %>
</p>

<p>
  <b>Date and time:</b>
  <%= @photo.Date_and_time %>
</p>

<p>
  <b>Photographer name:</b>
  <%= @photo.Photographer_name %>
</p>

<p>
  <b>Image url:</b>
  <%= @photo.image_url %>
</p>
<p>
  <b>Original image url:</b>
  <%= @photo.original_image_url %>
</p>

<p>
  <b>Single price:</b>
  <%= @photo.single_price %>
</p>

<p>
  <b>Outright price:</b>
  <%= @photo.outright_price %>
</p>


<%= link_to 'Edit', edit_photo_path(@photo) %> |
<%= link_to 'Back', photos_path %>