config/routes.rb
Photograph::Application.routes.draw do
 
 

  get "adminusersession/create"

  get "adminusersession/destroy"

  

  resources :adminusers

  resources :mainusers

  get 'adminuserpage' => 'adminuserpage#index'

  controller :adminusersession do
    get 'adminuserlogin' => :new
    post 'adminuserlogin' => :create
   delete 'adminuserlogout' => :destroy
  end

  get 'mainuserpage' => 'mainuserpage#index'

  controller :mainusersession do
    get 'userlogin' => :new
    post 'userlogin' => :create
   delete 'userlogout' => :destroy
  end

    get 'admin' => 'admin#index'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
   delete 'logout' => :destroy
end

  scope '(:locale)' do
  resources :users

  resources :orders

  resources :line_items

  resources :carts
  
  resources :photos do
    get :who_bought, :on => :member
    get :sample_image, :on => :member
    get :original_image, :on => :member
    
  end

  root :to => 'store#index', :as => 'store'

  end
  get "sessions/new"
  get "sessions/create"
  get "sessions/destroy"
  get "store/index"

end

app/controllers/store_controller.rb
class StoreController < ApplicationController
  skip_before_filter :authorize
  skip_before_filter :userauthorize
  def index
    #to get the photos from the database with the search
    @photos = Photo.search(params[:search])
    if params[:set_locale]
    redirect_to store_path(:locale => params[:set_locale])
    else
     @photos=   Photo.paginate :page=>params[:page], :order=>'created_at asc',
               :per_page => 5
    @cart = current_cart
   end
 end
end

app/views/store/index.html.erb
<% if notice %>

<p id="notice" ><%= notice %></p>
<% end %>

<% form_tag photos_path, :method => 'get' do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :Title => nil, :Photographer_name =>nil %>
  </p>
<% end %>

  <h1><%= t('.title_html') %></h1>

<% @photos.each do |photo| %>
<div class="entry" >
<h3><%= photo.Title %></h3>
<%= image_tag(photo.image_url) %>
<b> Description  </b> <%= sanitize(photo.Description) %>
<p><b> Location  </b> <%= (photo.Location) %></p>
<p><b> date and time  </b> <%= (photo.Date_and_time)%></p>
<p><b> Photographed by  </b> <%= (photo.Photographer_name)  %></p>
<div class="price_line" >
  <span class="price" ><b> single price  </b><%= number_to_currency(photo.single_price) %></span>
     <%if session[:user_id]%>
  <p><%= button_to t('.single_add_html'), line_items_path(:photo_id => photo, :purcahse_type=>0),
      :remote => true %></p>
   <%  end %>
  <%if session[:mainuser_id]%>
  <p><%= button_to t('.single_add_html'), line_items_path(:photo_id => photo, :purcahse_type=>0),
      :remote => true %></p>
   <%  end %>
  <%if session[:mainadmin_id]%>
  <p><%= button_to t('.single_add_html'), line_items_path(:photo_id => photo, :purcahse_type=>0),
      :remote => true %></p>
   <%  end %>
  <div class="price_line1" >
  <p><span class="price" ><b> outright price  </b><%= number_to_currency(photo.outright_price) %></span></p>
  <%if session[:user_id]%>
  <p><%= button_to t('.outright_add_html'), line_items_path(:photo_id => photo, :purchase_type =>1),
      :remote => true %></p>
  <% end  %>
  <%if session[:mainuser_id]%>
  <p><%= button_to t('.outright_add_html'), line_items_path(:photo_id => photo, :purchase_type =>1),
      :remote => true %></p>
  <% end  %>
  <%if session[:mainadmin_id]%>
  <p><%= button_to t('.outright_add_html'), line_items_path(:photo_id => photo, :purchase_type =>1),
      :remote => true %></p>
  <% end  %>

</div>

</div>
</div>

<% end %>
<p><%= will_paginate @photos %></p>