config/routes.rb
Photograph::Application.routes.draw do
 
 

  get "adminusersession/create"

  get "adminusersession/destroy"

  

  resources :adminusers

  resources :mainusers

  get 'adminuserpage' => 'adminuserpage#index'

  controller :adminusersession do
    get 'adminuserlogin' => :new
    post 'adminuserlogin' => :create
   delete 'adminuserlogout' => :destroy
  end

  get 'mainuserpage' => 'mainuserpage#index'

  controller :mainusersession do
    get 'userlogin' => :new
    post 'userlogin' => :create
   delete 'userlogout' => :destroy
  end

    get 'admin' => 'admin#index'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
   delete 'logout' => :destroy
end

  scope '(:locale)' do
  resources :users

  resources :orders

  resources :line_items

  resources :carts
  
  resources :photos do
    get :who_bought, :on => :member
    get :sample_image, :on => :member
    get :original_image, :on => :member
    
  end

  root :to => 'store#index', :as => 'store'

  end
  get "sessions/new"
  get "sessions/create"
  get "sessions/destroy"
  get "store/index"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title> Photograph </title>
<!-- START:stylesheet -->
  <%= stylesheet_link_tag "scaffold" %>
  <%= stylesheet_link_tag "photo", :media => "all" %><!-- <label id="code.slt"/> -->
<!-- END:stylesheet -->
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %><!-- <label id="code.csrf"/> -->
</head>
<body id="store">
  <div id="banner">
    <%= form_tag store_path, :class => 'locale' do %>
<%= select_tag 'set_locale',
options_for_select(LANGUAGES, I18n.locale.to_s),
:onchange => 'this.form.submit()' %>
<%= submit_tag 'submit' %>
<%= javascript_tag "$$('.locale input').each(Element.hide)" %>
<% end %>

  <%= @page_title || t('.title') %><!-- <label id="code.depot.e.title"/> -->
  </div>
  
  <div id="columns">
    <div id="side">
      <% if @cart %>
        <%= hidden_div_if(@cart.line_items.empty?, :id => "cart") do %>
        <%= render @cart %>
      <% end %>
    <% end %>
  <a href="http://localhost:3000/" ><%= t('.home') %></a><br />
<a href="http://localhost:3000/news" ><%= t('.news') %></a><br />
<a href="http://localhost:3000/contacts" ><%= t('.contact') %></a><br />
<a href="http://localhost:3000/mainusers/new" ><%= t('.sign up') %></a><br />
<a href="http://localhost:3000/adminuserlogin" ><%= t('.admin') %></a><br />
<a href="http://localhost:3000/login" ><%= t('.staff') %></a><br />
<% if session[:adminuser_id] %>
<a href="http://localhost:3000/userlogin" ><%= t('.user sign in') %></a><br />
<a href="http://localhost:3000/login" ><%= t('.staff') %></a><br />
<% end %>
<% if session[:user_id] %>
<br />
<%= link_to 'Orders', orders_path %><br />
<%= link_to 'Photos', photos_path %><br />
<%= link_to 'user', mainusers_path %><br />
<br />
<%= button_to ' staff Logout', logout_path, :method => :delete %>
<% end %>

<% if session[:adminuser_id] %>
<br />
<%= link_to 'Orders', orders_path %><br />
<%= link_to 'Photos', photos_path %><br />
<%= link_to 'user', mainusers_path %><br />
<%= link_to 'staff', users_path  %>
<br />
<% end  %>
<% if session[:adminuser_id] %>
   <br/>
<%= button_to ' admin Logout', adminuserlogout_path, :method => :delete %>
<% end %>

<% if session[:mainuser_id] %>
  <br />
  <%= button_to 'user Logout', userlogout_path, :method => :delete %>
<% end %>
</div>
<div id="main" >
<%= yield %>
</div>
    </div>
</body>
</html>